theme: jekyll-theme-slate
title: [CertifiedTrue]
description: [CertifiedTrue is a public/private consortium created to advance blockchain certification in Legal &#x2c; Real Estate and Insurance &#46;]
show_downloads: false
github:
  is_project_page: false
