theme: jekyll-theme-slate
title: [CertifiedTrue]
description: [CertifiedTrue is a public/private consortium created to advance blockchain certification in Legal', 'Real Estate and Insurance.]
show_downloads: false
github:
  is_project_page: false
