theme: jekyll-theme-slate
title: [CertifiedTrue]
description: [CertifiedTrue is a public&#47;private consortium created to advance blockchain certification in Legal&#x2c;Insurance and Real Estate&#46;]
show_downloads: false
github:
  is_project_page: false
